name: Run Unit Tests

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev

      - name: Compile and run tests
        run: |
          gcc -o calculator.o calculator.c
          gcc -o test test.c -lcunit
          ./test
