name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile and run unit tests
      run: |
        make ./test 

#1